---
    name: Publish to hex.pm
    
    on:
      push:
        tags:
          - "*"
    
    env:
        PROJECTS_INFO: W3t9XQ==
        GOOGLE_CREDENTIALS: W3t9XQ==
    
    jobs:
      publish-hexpm:
        name: publish to hex.pm
        runs-on: ubuntu-latest
        container: elixir:1.14-alpine
        steps:
          - uses: actions/checkout@v2
          - name: Install dependencies
            run: |
              apk add --update bash openssl git
              mix local.hex --force && mix local.rebar --force
          - name: Install elixir dependencies
            run: mix deps.get
          - name: publish to hex.pm
            run: mix hex.publish --yes
            env:
              HEX_API_KEY: ${{ secrets.HEX_KEY_PUBLISH }}
              